// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hldmtoefzibzemdojgdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsZG10b2VmemliemVtZG9qZ2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjIyNzgsImV4cCI6MjA2MDg5ODI3OH0.w60951Nq9bnrs4E2xJkX7vo7HYLKeukWR4H1cEqOP0E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);